cat-cashback:
  mob-spawn-egg-cashback: 10
  return-inv-cashback: 100
  shop:
    enabled: true
    price: 8000
  name: "§x§f§f§a§1§6§cПушистый Кэшбэк"
  lore:
    - ""
    - "§x§3§9§f§f§a§0100% кэшбэк на услуги хранителя"
    - ""
    - "§7Осторожно! Если убежит к противникам, эффект перейдёт к ним."
    - "§7Если погибнет любым способом, эффект пропадет!"

exp-wither:
  shop:
    enabled: true
    price: 25000
  name: "§x§6§1§5§b§a§5Болезненный опыт"
  lore:
    - ""
    - "§x§6§1§5§b§a§5В 50 раз больше выпадаемого опыта из мобов"
    - ""
    - "§7Осторожно! Если убежит к противникам, эффект перейдёт к ним."
    - "§7Если погибнет любым способом, эффект пропадет!"
    - "§x§f§6§3§a§3§aКусается ;c"

cow-double:
  shop:
    enabled: true
    price: 5000
  name: "§x§f§b§6§8§6§8Двойной бекон"
  lore:
    - ""
    - "§x§f§b§6§8§6§8Удваивает выпадение мяса со всех Ваших коров"
    - ""
    - "§7Осторожно! Если убежит к противникам, эффект перейдёт к ним."
    - "§7Если погибнет любым способом, эффект пропадет!"

shop-lore-footer:
  - ""
  - "§fЦена: %price%"
  - "§x§3§9§f§f§a§0Нажмите, чтобы приобрести"

messages:
  cashback: "Вы получили кэшбэк %price%$"